apiVersion: apps/v1
kind: Deployment
metadata:
  name: weight-tracker
  labels:
    app: weight-tracker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weight-tracker
  template:
    metadata:
      labels:
        app: weight-tracker
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - image: shayregistryweighttracker.azurecr.io/k8s
        name: weight-tracker
        env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: env
              key: pghost
        - name: PGUSERNAME
          valueFrom:
            secretKeyRef:
              name: env
              key: pg_username
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: env
              key: pg_password
        - name: OKTA_ORG_URL
          valueFrom:
            secretKeyRef:
              name: env
              key: okta_url
        - name: OKTA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: env
              key: okta_client_secret
        - name: OKTA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: env
              key: okta_client_id
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: env
              key: PORT
        - name: COOKIE_ENCRYPT_PWD
          valueFrom:
            secretKeyRef:
              name: env
              key: COOKIE_ENCRYPT_PWD
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: env
              key: host
        - name: HOST_URL
          valueFrom:
            secretKeyRef:
              name: env
              key: HOST_URL
              
        
